pext/__main__.py

For upstream

---

README.md

Let me know if it is too detailed or something. Also, there might be some wonkiness with the commits, because to not have the pext/pext.py commits I overrode those for the readme branch, but the commits still show in history :-/

Updated Readme for experimental windows support

---

pext/git_describe.py

Fixes Travis builds in #31.
```
pext/git_describe.py:28:1: E302 expected 2 blank lines, found 1

Fix PEP8 E302

---

MANIFEST.in
setup.py
test/test.py

I had to disable `include_package_data` in setup.py, otherwise package won't be included in sdist build.

Add tests for LocaleManager

---

pext/__main__.py
pext/qml/main.qml
travis/build-appimage.sh

This PR shall:
- reduce the AppImage size
- add features to the AppImage
- add support for AppImageUpdate
Please do not merge until further notice.

Improve AppImage

---

README.md

Re-arranged readme, so that newcomers can see how it works more easily

Re-arranged readme

---

travis/build-appimage.sh

Add version support to Pext AppImage

---

.travis.yml
setup.py
travis/bootstrap-container.sh
travis/build-appimage.sh
travis/build-dmg.sh

Remove unused Qt modules from AppImage

---

pext/__main__.py

All existing modules need to be updated before it can be merged

Allow multiword commands

---

README.md
pext/__main__.py
pext/qml/CommandArgsDialog.qml
pext/qml/ModuleData.qml
pext/qml/main.qml

This commit finally fixes handling of multi-word commands

New method for command argument handling

---

pext/qml/main.qml

Fixed typo in localisation string depencencies -> dependencies

fixed typo in tr string

---

pext/__main__.py
requirements.txt

Cross platform pid identification.

moved pid identification to psutil

---

.appveyor.yml

moved from single to double quoted statement

---

.appveyor.yml

By installing for all users instead of just the administrator.

Fix Windows shortcut (#220)

---

pext/qml/main.qml

Fix typo in property string identifier

---

pext/qml/AboutDialog.qml
pext/qml/ChoiceDialog.qml
pext/qml/CommandArgsDialog.qml
pext/qml/ConfirmQuitDialog.qml
pext/qml/CriticalErrorDialog.qml
pext/qml/InputRequestDialog.qml
pext/qml/InstallFromRepositoryDialog.qml
pext/qml/InstallModuleFromRepositoryNoModulesAvailableDialog.qml
pext/qml/InstallModuleFromRepositorySelectModuleDialog.qml
pext/qml/InstallModuleFromURLDialog.qml
pext/qml/InstallThemeFromURLDialog.qml
pext/qml/LoadModuleDialog.qml
pext/qml/LoadProfileDialog.qml
pext/qml/LoadThemeDialog.qml
pext/qml/ManageDialog.qml
pext/qml/ManageProfilesDialog.qml
pext/qml/NoModulesInstalledDialog.qml
pext/qml/NoThemesInstalledDialog.qml
pext/qml/OnlyOneProfileDialog.qml
pext/qml/QuestionDialog.qml
pext/qml/RenameProfileDialog.qml

WIP: Destroying windows when they are closed

---

pext/qml/ModuleData.qml

Spelling: A module has crashed

---

pext/__main__.py

Sorry if this doesn't follow guidelines, I didn't have chance to review all of the developer documentation yet.
Just suggesting a quick fix for issue #322.

Check for pip problems only in Debian Strech and below.

---

pext/__main__.py
pext/ui/qt5.py
setup.py

python package after build doesn't contain `ui` module

Fix ui module packaging

---

pext/ui/qt5.py

qt expects a integer there and i observed a segfault due to it

use truediv to set window geometry

---

.appveyor.yml
.github/workflows/main.yml
setup.py

Fix version generation in CI
